### ISSUE TITLE
exit_fail(ed): make the APIs consistent

### ISSUE THREAD

**Issue by bocekm** [upgrades-migrations/preupgrade-assistant#199]
Currently python API has a function _exit_failed_ and bash API has _exit_fail_. Fix this inconsistency.

**Comment by AloisMahdal** [comment]
Turns out that Bash API has `exit_fail()` but the python API has *both*.

Note that the naming is not very consistent even within API:

    $ shellfu-doc --lsfun ./common.sh  | grep exit_
    common.exit_error
    common.exit_fail
    common.exit_fixed
    common.exit_informational
    common.exit_not_applicable
    common.exit_pass
    $

"pass" and "fail" are imperative, "fixed", "informational" and "not_applicable" are adjective, "error" is a noun.

One of these days we should just revamp the states (not just API but also module results; I find "fixed" confusing as I have <strike>ranted</strike> pointed out elsewhere) into something more intuitive and consistent.
