### ISSUE TITLE
Move to pykickstart-3

### ISSUE THREAD

**Issue by clumens** [upgrades-migrations/preupgrade-assistant#347]
Over the past two years, I've been working on a new version of pykickstart that cleans up a bunch of stuff and corrects some inherent flaws, as well as stops using certain deprecated python modules. The result is that there are some incompatibilities between v2 and v3. The projects that are most affected are the ones that really dig in and do a lot of custom stuff. It's been in the works a long time now and with anaconda starting to adapt, I feel like it's probably time to get rid of pykickstart-2 and use pykickstart-3 in Fedora.

There is a copr with the new version here: https://copr.fedorainfracloud.org/coprs/clumens/pykickstart-3/, and there's a document describing the changes here: https://github.com/rhinstaller/pykickstart/blob/master/docs/2to3.

preupgrade-assistant looks like it uses pykickstart fairly extensively, but perhaps really just for generating kickstart files so maybe with a little luck there's not much to do here.  I would be happy to develop patches if there's a way to test preupgrade-assistant against the copr repo.  Also, I'd like to note that this is only for the future - RHEL7 and before is always going to be pykickstart-2.  How should we proceed?

**Comment by bocekm** [comment]
Thanks Chris for letting us know. We won't be adapting the new pykickstart-3 in the Preupgrade Assistant because of numerous reasons:
- The kickstart-generating feature of the Preupgrade Assistant was actually used only for migrations of RHEL 5 to RHEL 7
- When it comes to migrating to RHEL 8, most probably we'll not be using kickstart, but if we do we'll be doing that in another tool (Leapp) where we can adopt your new pykickstart-3
- We will drop the Preupgrade Assistant package from Fedora completely, it's really old version there and we do not plan to provide the new version there.

**Comment by clumens** [comment]
Okay, cool.  Thanks for the info.  I'll remove you from my list of projects that need work then.  If you do end up doing anything with kickstart for RHEL8 and need help or additional functionality or anything, please don't hesitate to get in touch with me.
